### ISSUE TITLE
Getting no module named 'route1io_connectors.google.utils'

### ISSUE THREAD

**Issue by Kendiroute1** [route1io/route1io-python-connectors#48]
**Describe the bug**
I'm getting a "No module named 'route1io_connectors.google.utils'" when running Google Analytics

**To Reproduce**
1. import "from route1io_connectors.google import google_analytics "
2. run the script
3. get error "from .utils import _universal_analytics, _ga4
ModuleNotFoundError: No module named 'route1io_connectors.google.utils'"

**Expected behavior**
No error should be present since we are just importing a pythong script.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
is it possible that the issue id due to line 11 given that .utils is a folder and not a script?
![image](https://user-images.githubusercontent.com/105944155/220123445-4d7ecb81-3d3c-4adf-a1fa-d03ca6c9e03d.png)

**Comment by chris-greening** [comment]
Hey @Kendiroute1 thanks for flagging - funnily enough I caught the exact same error and fixed it before even reading this issue haha this should be fixed now, please reinstall version 0.15.2 to get the fix

The `google.utils` subpackage didn't have an `__init__.py` and thus `setuptools.find_packages` in `setup.py` didn't register it as a package when uploading to PyPI 

Cheers
